import type { TankDashboardData } from '@/types'

export const MOCK_DASHBOARD: TankDashboardData[] = [
  {
    tank: { id: 'fv1', name: 'FV1', type: 'fermenter', frigid_tank_name: 'FV1', sort_order: 1 },
    brew: { id: 'b1', recipe_id: 'r1', tank_id: 'fv1', brew_day: '2026-04-20', volume_l: 2800, og_plato: 16.5, stage: 'active_ferment', beer_name: 'Golden Ratio', style: 'Hazy IPA / NEIPA', notes: null },
    latest_gravity: { id: 'g1', brew_id: 'b1', tank_id: 'fv1', recorded_at: '2026-04-27T08:00:00Z', plato: 8.2, ph: 4.3, recorded_by: 'Carla', notes: null },
    temperature: 18.5,
    temperature_recorded_at: new Date().toISOString(),
    days_in_tank: 8,
  },
  {
    tank: { id: 'fv2', name: 'FV2', type: 'fermenter', frigid_tank_name: 'FV2', sort_order: 2 },
    brew: null,
    latest_gravity: null,
    temperature: 18.2,
    temperature_recorded_at: new Date().toISOString(),
    days_in_tank: null,
  },
  {
    tank: { id: 'fv3', name: 'FV3', type: 'fermenter', frigid_tank_name: 'FV3', sort_order: 3 },
    brew: { id: 'b3', recipe_id: 'r3', tank_id: 'fv3', brew_day: '2026-04-15', volume_l: 3000, og_plato: 15.8, stage: 'on_chill', beer_name: 'Golden Ratio', style: 'Hazy IPA / NEIPA', notes: null },
    latest_gravity: { id: 'g3', brew_id: 'b3', tank_id: 'fv3', recorded_at: '2026-04-26T09:00:00Z', plato: 3.1, ph: 4.1, recorded_by: 'Zac', notes: null },
    temperature: 2.0,
    temperature_recorded_at: new Date().toISOString(),
    days_in_tank: 13,
  },
  {
    tank: { id: 'fv4', name: 'FV4', type: 'fermenter', frigid_tank_name: 'FV4', sort_order: 4 },
    brew: { id: 'b4', recipe_id: 'r4', tank_id: 'fv4', brew_day: '2026-04-22', volume_l: 2600, og_plato: 18.2, stage: 'active_ferment', beer_name: 'Oat Cream', style: 'Hazy IPA / NEIPA', notes: null },
    latest_gravity: { id: 'g4', brew_id: 'b4', tank_id: 'fv4', recorded_at: '2026-04-27T10:00:00Z', plato: 10.5, ph: 4.5, recorded_by: 'Carla', notes: null },
    temperature: 20.3,
    temperature_recorded_at: new Date().toISOString(),
    days_in_tank: 6,
  },
  {
    tank: { id: 'fv5', name: 'FV5', type: 'fermenter', frigid_tank_name: 'FV5', sort_order: 5 },
    brew: { id: 'b5', recipe_id: 'r5', tank_id: 'fv5', brew_day: '2026-04-18', volume_l: 2900, og_plato: 13.5, stage: 'diacetyl_rest', beer_name: 'Hoodie Weather', style: 'Pale Ale', notes: null },
    latest_gravity: { id: 'g5', brew_id: 'b5', tank_id: 'fv5', recorded_at: '2026-04-27T07:00:00Z', plato: 4.8, ph: 4.2, recorded_by: 'Zac', notes: null },
    temperature: 18.7,
    temperature_recorded_at: new Date().toISOString(),
    days_in_tank: 10,
  },
  {
    tank: { id: 'fv6', name: 'FV6', type: 'fermenter', frigid_tank_name: 'FV6', sort_order: 6 },
    brew: { id: 'b6', recipe_id: 'r6', tank_id: 'fv6', brew_day: '2026-04-19', volume_l: 2800, og_plato: 13.5, stage: 'active_ferment', beer_name: 'Hoodie Weather', style: 'Pale Ale', notes: null },
    latest_gravity: { id: 'g6', brew_id: 'b6', tank_id: 'fv6', recorded_at: '2026-04-27T11:00:00Z', plato: 9.0, ph: 4.4, recorded_by: 'Carla', notes: null },
    temperature: 18.7,
    temperature_recorded_at: new Date().toISOString(),
    days_in_tank: 9,
  },
  {
    tank: { id: 'fv7', name: 'FV7', type: 'fermenter', frigid_tank_name: 'FV7', sort_order: 7 },
    brew: { id: 'b7', recipe_id: 'r7', tank_id: 'fv7', brew_day: '2026-04-21', volume_l: 2700, og_plato: 13.5, stage: 'vdk_pass', beer_name: 'Hoodie Weather', style: 'Pale Ale', notes: null },
    latest_gravity: { id: 'g7', brew_id: 'b7', tank_id: 'fv7', recorded_at: '2026-04-27T06:00:00Z', plato: 5.2, ph: 4.3, recorded_by: 'Zac', notes: null },
    temperature: 17.7,
    temperature_recorded_at: new Date().toISOString(),
    days_in_tank: 7,
  },
  {
    tank: { id: 'fv8', name: 'FV8', type: 'fermenter', frigid_tank_name: 'FV8', sort_order: 8 },
    brew: { id: 'b8', recipe_id: 'r8', tank_id: 'fv8', brew_day: '2026-04-14', volume_l: 3000, og_plato: null, stage: 'cleaning', beer_name: 'Party Shirt', style: 'IPA', notes: null },
    latest_gravity: null,
    temperature: 13.1,
    temperature_recorded_at: new Date().toISOString(),
    days_in_tank: 14,
  },
  {
    tank: { id: 'fv9', name: 'FV9', type: 'fermenter', frigid_tank_name: 'FV9', sort_order: 9 },
    brew: { id: 'b9', recipe_id: 'r9', tank_id: 'fv9', brew_day: '2026-04-23', volume_l: 2800, og_plato: 17.0, stage: 'active_ferment', beer_name: 'Party Shirt', style: 'IPA', notes: null },
    latest_gravity: { id: 'g9', brew_id: 'b9', tank_id: 'fv9', recorded_at: '2026-04-27T09:00:00Z', plato: 11.2, ph: 4.6, recorded_by: 'Carla', notes: null },
    temperature: 20.4,
    temperature_recorded_at: new Date().toISOString(),
    days_in_tank: 5,
  },
  {
    tank: { id: 'fv10', name: 'FV10', type: 'fermenter', frigid_tank_name: 'FV10', sort_order: 10 },
    brew: { id: 'b10', recipe_id: 'r10', tank_id: 'fv10', brew_day: '2026-04-12', volume_l: 2900, og_plato: 12.8, stage: 'ready', beer_name: 'WC Pils', style: 'Pilsner', notes: null },
    latest_gravity: { id: 'g10', brew_id: 'b10', tank_id: 'fv10', recorded_at: '2026-04-26T08:00:00Z', plato: 2.8, ph: 4.0, recorded_by: 'Zac', notes: null },
    temperature: 0.2,
    temperature_recorded_at: new Date().toISOString(),
    days_in_tank: 16,
  },
  {
    tank: { id: 'fv11', name: 'FV11', type: 'fermenter', frigid_tank_name: 'FV11', sort_order: 11 },
    brew: { id: 'b11', recipe_id: 'r11', tank_id: 'fv11', brew_day: '2026-04-24', volume_l: 2800, og_plato: 17.0, stage: 'active_ferment', beer_name: 'Party Shirt', style: 'IPA', notes: null },
    latest_gravity: { id: 'g11', brew_id: 'b11', tank_id: 'fv11', recorded_at: '2026-04-27T12:00:00Z', plato: 12.0, ph: 4.7, recorded_by: 'Carla', notes: null },
    temperature: 0.2,
    temperature_recorded_at: new Date().toISOString(),
    days_in_tank: 4,
  },
  {
    tank: { id: 'bbt-a', name: 'BBT A', type: 'brite', frigid_tank_name: 'BRITE A', sort_order: 12 },
    brew: null,
    latest_gravity: null,
    temperature: 18.0,
    temperature_recorded_at: new Date(Date.now() - 25 * 60000).toISOString(),
    days_in_tank: null,
  },
  {
    tank: { id: 'bbt-b', name: 'BBT B', type: 'brite', frigid_tank_name: 'BRITE B', sort_order: 13 },
    brew: { id: 'b13', recipe_id: 'r13', tank_id: 'bbt-b', brew_day: '2026-04-10', volume_l: 2400, og_plato: 11.2, stage: 'ready', beer_name: "Findon's Finest", style: 'Lager', notes: null },
    latest_gravity: { id: 'g13', brew_id: 'b13', tank_id: 'bbt-b', recorded_at: '2026-04-27T07:00:00Z', plato: 2.2, ph: 4.1, recorded_by: 'Zac', notes: null },
    temperature: 0.8,
    temperature_recorded_at: new Date().toISOString(),
    days_in_tank: 18,
  },
]
